In [57]:
import pandas as pd

In [58]:
import numpy as np

In [59]:
df = pd.read_csv("future_jobs_dataset.csv")
df.head()

,job_id,job_title,industry,location,salary_usd,skills_required,remote_option,company_size,posting_date
0,1,Quantum Researcher,Quantum Computing,Singapore,175780,"Linear Algebra, Quantum Algorithms",No,Large,2025-07-22
1,2,Renewable Energy Engineer,Green Tech,Singapore,137481,"Climate Data Analysis, Energy Modeling",Yes,Large,2025-09-26
2,3,Quantum Researcher,Quantum Computing,Tokyo,182081,"Linear Algebra, Qiskit",No,Medium,2025-12-31
3,4,Sustainability Analyst,Green Tech,Singapore,113822,"Climate Data Analysis, Energy Modeling",No,Large,2025-05-29
4,5,Smart Contract Engineer,Blockchain,London,92575,"Rust, Solidity",Yes,Small,2025-03-30

In [60]:
df.isnull().sum()

job_id             0
job_title          0
industry           0
location           0
salary_usd         0
skills_required    0
remote_option      0
company_size       0
posting_date       0
dtype: int64

In [61]:
df.dtypes

job_id              int64
job_title          object
industry           object
location           object
salary_usd          int64
skills_required    object
remote_option      object
company_size       object
posting_date       object
dtype: object

In [62]:
import sklearn
from sklearn.datasets import load_diabetes
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [63]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [64]:
import sqlite3

In [65]:
cnn = sqlite3.connect('new_sql_db')

In [66]:
execute_sql = cnn.cursor()

In [67]:
df.to_sql('jobs',con = cnn, if_exists = 'replace')

10000

In [68]:
result = pd.read_sql("""SELECT * FROM jobs""",
                     con = cnn)

In [69]:
result

,index,job_id,job_title,industry,location,salary_usd,skills_required,remote_option,company_size,posting_date
0,0,1,Quantum Researcher,Quantum Computing,Singapore,175780,"Linear Algebra, Quantum Algorithms",No,Large,2025-07-22
1,1,2,Renewable Energy Engineer,Green Tech,Singapore,137481,"Climate Data Analysis, Energy Modeling",Yes,Large,2025-09-26
2,2,3,Quantum Researcher,Quantum Computing,Tokyo,182081,"Linear Algebra, Qiskit",No,Medium,2025-12-31
3,3,4,Sustainability Analyst,Green Tech,Singapore,113822,"Climate Data Analysis, Energy Modeling",No,Large,2025-05-29
4,4,5,Smart Contract Engineer,Blockchain,London,92575,"Rust, Solidity",Yes,Small,2025-03-30
...,...,...,...,...,...,...,...,...,...,...
9995,9995,9996,Sustainability Analyst,Green Tech,New York,248617,"Energy Modeling, Climate Data Analysis",Yes,Small,2025-04-13
9996,9996,9997,Blockchain Developer,Blockchain,New York,104410,"Ethereum, Solidity",Yes,Large,2025-11-03
9997,9997,9998,Quantum Software Developer,Quantum Computing,Berlin,200382,"Quantum Algorithms, Qiskit",No,Small,2025-02-23
9998,9998,9999,Renewable Energy Engineer,Green Tech,New York,214484,"Energy Modeling, Climate Data Analysis",No,Small,2025-03-08
9999,9999,10000,AI Engineer,AI,Singapore,117307,"TensorFlow, Python",Yes,Large,2025-08-12

In [70]:
cols = df.columns
cols

Index(['job_id', 'job_title', 'industry', 'location', 'salary_usd',
       'skills_required', 'remote_option', 'company_size', 'posting_date'],
      dtype='object')

In [89]:
df.dtypes

job_id              int64
job_title          object
industry           object
location           object
salary_usd          int64
skills_required    object
remote_option      object
company_size       object
posting_date       object
dtype: object

In [113]:
#job_titles
result = pd.read_sql("""SELECT DISTINCT job_title 
                        FROM jobs
                        """,
                     con = cnn)

In [115]:
result

                    job_title
0          Quantum Researcher
1   Renewable Energy Engineer
2      Sustainability Analyst
3     Smart Contract Engineer
4  Quantum Software Developer
5        Blockchain Developer
6                 AI Engineer
7              Data Scientist
8               ML Researcher

In [117]:
#Total Jobs Per Country
result = pd.read_sql("""SELECT location, 
                        COUNT(*) AS Total_jobs_per_country
                        FROM jobs
                        GROUP BY  location""",
                     con = cnn)

In [119]:
result

    location  Total_jobs_per_country
0     Berlin                    1640
1      Dubai                    1660
2     London                    1656
3   New York                    1689
4  Singapore                    1682
5      Tokyo                    1673

In [147]:
#Average Salary by Industry
result = pd.read_sql("""SELECT industry, 
                        ROUND(AVG(salary_usd),2) AS avg_salary
                        FROM jobs
                        GROUP BY industry""",
                     con = cnn)

In [149]:
result

            industry  avg_salary
0                 AI   150672.37
1         Blockchain   149383.77
2         Green Tech   149329.90
3  Quantum Computing   151130.70

In [151]:
#Average Salary by Job Title
result = pd.read_sql("""SELECT job_title, 
                        ROUND(AVG(salary_usd),2) AS avg_salary
                        FROM jobs
                        GROUP BY job_title
                        ORDER BY avg_salary DESC""",
                     con = cnn)

In [153]:
result

                    job_title  avg_salary
0  Quantum Software Developer   151499.84
1               ML Researcher   151284.99
2      Sustainability Analyst   150991.59
3              Data Scientist   150990.36
4     Smart Contract Engineer   150779.20
5          Quantum Researcher   150750.54
6                 AI Engineer   149794.91
7        Blockchain Developer   147975.99
8   Renewable Energy Engineer   147689.43

In [141]:
cols

Index(['job_id', 'job_title', 'industry', 'location', 'salary_usd',
       'skills_required', 'remote_option', 'company_size', 'posting_date'],
      dtype='object')

In [155]:
#Average Salary by Location
result = pd.read_sql("""SELECT location, 
                        ROUND(AVG(salary_usd),2) AS avg_salary
                        FROM jobs
                        GROUP BY location
                        ORDER BY avg_salary DESC""",
                     con = cnn)

In [157]:
result

    location  avg_salary
0   New York   152266.60
1     London   152260.96
2     Berlin   150194.84
3      Dubai   149483.85
4  Singapore   148622.50
5      Tokyo   147965.94

In [159]:
#Salary Range Based on Industry
result = pd.read_sql("""SELECT 'Industry' AS category, 
                          industry AS group_name, 
                          MIN(salary_usd) AS min_salary, 
                          MAX(salary_usd) AS max_salary, 
                          MAX(salary_usd) - MIN(salary_usd) AS salary_range 
                    FROM jobs GROUP BY industry
                        UNION ALL
                      SELECT 'Job Title' AS category, 
                            job_title  AS group_name, 
                            MIN(salary_usd) AS min_salary, 
                            MAX(salary_usd) AS max_salary, 
                            MAX(salary_usd) - MIN(salary_usd) AS salary_range 
                    FROM jobs GROUP BY job_title
                    ORDER BY category, salary_range DESC;""",
                     con = cnn)

In [161]:
result

,category,group_name,min_salary,max_salary,salary_range
0,Industry,Blockchain,50060,249990,199930
1,Industry,AI,50060,249952,199892
2,Industry,Quantum Computing,50013,249766,199753
3,Industry,Green Tech,50072,249809,199737
4,Job Title,Data Scientist,50061,249952,199891
5,Job Title,ML Researcher,50060,249893,199833
6,Job Title,Quantum Software Developer,50013,249766,199753
7,Job Title,Blockchain Developer,50060,249810,199750
8,Job Title,AI Engineer,50159,249886,199727
9,Job Title,Sustainability Analyst,50172,249809,199637
10,Job Title,Quantum Researcher,50079,249674,199595
11,Job Title,Renewable Energy Engineer,50072,249504,199432
12,Job Title,Smart Contract Engineer,50692,249990,199298

In [187]:
result = pd.read_sql("""SELECT 
                        MIN(salary_usd) AS min_salary,
                        MAX(salary_usd) AS max_salary
                        FROM jobs""",
                        con = cnn)

In [189]:
result

   min_salary  max_salary
0       50013      249990

In [191]:
cols

Index(['job_id', 'job_title', 'industry', 'location', 'salary_usd',
       'skills_required', 'remote_option', 'company_size', 'posting_date'],
      dtype='object')

In [193]:
#Salary Gap between Remote and Non Remote Jobs
result = pd.read_sql("""SELECT remote_option,
                           COUNT(*) AS total_jobs,
                           ROUND(AVG(salary_usd), 2) AS avg_salary,
                           MIN(salary_usd) AS min_salary,
                           MAX(salary_usd) AS max_salary
                       FROM jobs
                       GROUP BY remote_option
                       ORDER BY avg_salary DESC """,
                      con = cnn)

In [195]:
result

  remote_option  total_jobs  avg_salary  min_salary  max_salary
0            No        4911   150469.45       50060      249990
1           Yes        5089   149805.42       50013      249985

In [197]:
#Salary Gap between Remote and Non Remote Jobs
result = pd.read_sql("""SELECT job_title,
                           ROUND(AVG(CASE WHEN remote_option = 'Yes' THEN salary_usd END), 2) AS avg_remote_salary,
                           ROUND(AVG(CASE WHEN remote_option = 'No'  THEN salary_usd END), 2) AS avg_onsite_salary,
                           ROUND(AVG(CASE WHEN remote_option = 'Yes' THEN salary_usd END) -
                           AVG(CASE WHEN remote_option = 'No'  THEN salary_usd END), 2) AS salary_gap
                        FROM jobs
                        GROUP BY job_title
                        ORDER BY salary_gap DESC""",
                        con = cnn)

In [199]:
result

,job_title,avg_remote_salary,avg_onsite_salary,salary_gap
0,Quantum Software Developer,152693.94,150263.91,2430.02
1,ML Researcher,152148.51,150336.67,1811.84
2,Blockchain Developer,148607.35,147302.68,1304.67
3,Quantum Researcher,150929.40,150564.93,364.47
4,Renewable Energy Engineer,147800.03,147574.69,225.34
5,Sustainability Analyst,150107.62,151924.02,-1816.41
6,Smart Contract Engineer,149065.46,152568.31,-3502.86
7,AI Engineer,147665.96,151600.19,-3934.22
8,Data Scientist,148862.49,153354.67,-4492.19

In [201]:
cols

Index(['job_id', 'job_title', 'industry', 'location', 'salary_usd',
       'skills_required', 'remote_option', 'company_size', 'posting_date'],
      dtype='object')

In [227]:
#Highest paid jobs according to Cities
result = pd.read_sql("""SELECT
                        location,
                        COUNT(*) as total_jobs,
                        MAX(salary_usd) as highest_paid
                        FROM jobs
                        GROUP BY location
                        ORDER BY highest_paid DESC""",
                        con = cnn)

In [229]:
result

    location  total_jobs  highest_paid
0   New York        1689        249990
1  Singapore        1682        249985
2      Tokyo        1673        249984
3      Dubai        1660        249952
4     Berlin        1640        249893
5     London        1656        249885

In [231]:
cols

Index(['job_id', 'job_title', 'industry', 'location', 'salary_usd',
       'skills_required', 'remote_option', 'company_size', 'posting_date'],
      dtype='object')

In [237]:
#City with Specific Industries
result = pd.read_sql("""SELECT 
                        location,
                        industry,
                        COUNT(*) AS total_jobs
                        FROM jobs
                        GROUP BY location, industry
                        ORDER BY industry, total_jobs DESC""",
                        con = cnn)

In [239]:
result

     location           industry  total_jobs
0       Dubai                 AI         429
1   Singapore                 AI         429
2       Tokyo                 AI         427
3    New York                 AI         413
4      Berlin                 AI         405
5      London                 AI         389
6   Singapore         Blockchain         432
7       Tokyo         Blockchain         429
8      London         Blockchain         423
9    New York         Blockchain         423
10     Berlin         Blockchain         406
11      Dubai         Blockchain         386
12   New York         Green Tech         429
13      Dubai         Green Tech         428
14  Singapore         Green Tech         413
15     Berlin         Green Tech         410
16      Tokyo         Green Tech         410
17     London         Green Tech         400
18     London  Quantum Computing         444
19   New York  Quantum Computing         424
20     Berlin  Quantum Computing         419
21      Dubai  Quantum Computing         417
22  Singapore  Quantum Computing         408
23      Tokyo  Quantum Computing         407

In [246]:
#Top 10 Demanding Skills
result = pd.read_sql("""SELECT skill,
                        COUNT(*) AS demand_count,
                        ROUND(AVG(salary_usd), 2) AS avg_salary,
                        MIN(salary_usd) AS min_salary,
                        MAX(salary_usd) AS max_salary
                        FROM (
                                SELECT salary_usd,
                                TRIM(value) AS skill
                                FROM jobs, json_each('["' || REPLACE(skills_required, ', ', '","') || '"]')
                                )
                        GROUP BY skill
                        ORDER BY avg_salary DESC
                        LIMIT 10""",
                        con = cnn)

In [248]:
result

                   skill  demand_count  avg_salary  min_salary  max_salary
0                 Qiskit          1682   152261.04       50013      249634
1                 Python          1657   151654.79       50061      249952
2     Quantum Algorithms          1690   150687.38       50013      249766
3         Linear Algebra          1666   150439.20       50079      249766
4                PyTorch          1637   150204.47       50060      249952
5             TensorFlow          1690   150162.36       50060      249886
6                   Rust          1646   149623.45       50692      249985
7               Solidity          1669   149482.70       50060      249990
8        Energy Modeling          2490   149329.90       50072      249809
9  Climate Data Analysis          2490   149329.90       50072      249809

In [250]:
df

,job_id,job_title,industry,location,salary_usd,skills_required,remote_option,company_size,posting_date
0,1,Quantum Researcher,Quantum Computing,Singapore,175780,"Linear Algebra, Quantum Algorithms",No,Large,2025-07-22
1,2,Renewable Energy Engineer,Green Tech,Singapore,137481,"Climate Data Analysis, Energy Modeling",Yes,Large,2025-09-26
2,3,Quantum Researcher,Quantum Computing,Tokyo,182081,"Linear Algebra, Qiskit",No,Medium,2025-12-31
3,4,Sustainability Analyst,Green Tech,Singapore,113822,"Climate Data Analysis, Energy Modeling",No,Large,2025-05-29
4,5,Smart Contract Engineer,Blockchain,London,92575,"Rust, Solidity",Yes,Small,2025-03-30
...,...,...,...,...,...,...,...,...,...
9995,9996,Sustainability Analyst,Green Tech,New York,248617,"Energy Modeling, Climate Data Analysis",Yes,Small,2025-04-13
9996,9997,Blockchain Developer,Blockchain,New York,104410,"Ethereum, Solidity",Yes,Large,2025-11-03
9997,9998,Quantum Software Developer,Quantum Computing,Berlin,200382,"Quantum Algorithms, Qiskit",No,Small,2025-02-23
9998,9999,Renewable Energy Engineer,Green Tech,New York,214484,"Energy Modeling, Climate Data Analysis",No,Small,2025-03-08
9999,10000,AI Engineer,AI,Singapore,117307,"TensorFlow, Python",Yes,Large,2025-08-12

In [ ]:
result = pd.read_sql("""SELECT 
                           job_title,
                           COUNT(*)
                        """,
                        con = cnn)